tags:
  - name: Status de termos
    description: Gerenciamento de status de termos

paths:
  /api/statustermos:
    get:
      summary: Lista todos os status de termos
      tags:
        - Status de termos
      responses:
        200:
          description: Lista retornada com sucesso
    post:
      summary: Cria um novo status de termo
      tags:
        - Status de termos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
      responses:
        201:
          description: Registro criado com sucesso

  /api/statustermos/filtros:
    get:
      summary: Busca status por filtros
      tags:
        - Status de termos
      responses:
        200:
          description: Registros filtrados com sucesso

  /api/statustermos/{id}:
    get:
      summary: Busca status por ID
      tags:
        - Status de termos
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Registro encontrado
    put:
      summary: Atualiza um status de termo por ID
      tags:
        - Status de termos
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
      responses:
        200:
          description: Registro atualizado com sucesso
    delete:
      summary: Remove um status por ID
      tags:
        - Status de termos
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Registro removido com sucesso
