tags:
  - name: Tipos de termos
    description: Gerenciamento de tipos de termos

paths:
  /api/tipostermos:
    get:
      summary: Lista todos os tipos de termos
      tags:
        - Tipos de termos
      responses:
        200:
          description: Lista retornada com sucesso
    post:
      summary: Cria um novo tipo de termo
      tags:
        - Tipos de termos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                descricao:
                  type: string
      responses:
        201:
          description: Registro criado com sucesso

  /api/tipostermos/filtros:
    get:
      summary: Busca tipos de termos por filtros
      tags:
        - Tipos de termos
      responses:
        200:
          description: Registros filtrados com sucesso

  /api/tipostermos/{id}:
    get:
      summary: Busca tipo de termo por ID
      tags:
        - Tipos de termos
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Registro encontrado
    put:
      summary: Atualiza um tipo de termo por ID
      tags:
        - Tipos de termos
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                descricao:
                  type: string
      responses:
        200:
          description: Registro atualizado com sucesso
    delete:
      summary: Remove um tipo de termo por ID
      tags:
        - Tipos de termos
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Registro removido com sucesso
