tags:
  - name: Categorias
    description: Gerenciamento de categorias de equipamentos

paths:
  /api/categoria:
    get:
      summary: Lista todas as categorias
      tags:
        - Categorias
      responses:
        200:
          description: Lista retornada com sucesso
    post:
      summary: Cria uma nova categoria
      tags:
        - Categorias
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                descricao:
                  type: string
      responses:
        201:
          description: Categoria criada com sucesso

  /api/categoria/filtros:
    get:
      summary: Busca categorias por filtros
      tags:
        - Categorias
      responses:
        200:
          description: Registros filtrados com sucesso

  /api/categoria/{id}:
    get:
      summary: Busca categoria por ID
      tags:
        - Categorias
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Categoria encontrada
    put:
      summary: Atualiza uma categoria por ID
      tags:
        - Categorias
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                descricao:
                  type: string
      responses:
        200:
          description: Categoria atualizada com sucesso
    delete:
      summary: Remove uma categoria por ID
      tags:
        - Categorias
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Categoria removida com sucesso
