tags:
  - name: Status de equipamento
    description: Gerenciamento de status de equipamentos

paths:
  /api/statusequipamentos:
    get:
      summary: Lista todos os status de equipamentos
      tags:
        - Status de equipamento
      responses:
        200:
          description: Lista retornada com sucesso
    post:
      summary: Cria um novo status de equipamento
      tags:
        - Status de equipamento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                descricao:
                  type: string
      responses:
        201:
          description: Status criado com sucesso

  /api/statusequipamentos/filtros:
    get:
      summary: Busca status por filtros
      tags:
        - Status de equipamento
      responses:
        200:
          description: Registros filtrados com sucesso

  /api/statusequipamentos/{id}:
    get:
      summary: Busca status por ID
      tags:
        - Status de equipamento
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Status encontrado
    put:
      summary: Atualiza um status por ID
      tags:
        - Status de equipamento
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                descricao:
                  type: string
      responses:
        200:
          description: Status atualizado com sucesso
    delete:
      summary: Remove um status por ID
      tags:
        - Status de equipamento
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Status removido com sucesso
