tags:
  - name: Equipamentos
    description: Gerenciamento de equipamentos

paths:
  /api/equipamento:
    get:
      summary: Lista todos os equipamentos
      tags:
        - Equipamentos
      responses:
        200:
          description: Lista retornada com sucesso
    post:
      summary: Cadastra um novo equipamento
      tags:
        - Equipamentos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numero_serie:
                  type: string
      responses:
        201:
          description: Equipamento cadastrado com sucesso

  /api/equipamento/filtros:
    get:
      summary: Busca equipamentos por filtros
      tags:
        - Equipamentos
      responses:
        200:
          description: Registros filtrados com sucesso

  /api/equipamento/{id}:
    get:
      summary: Busca equipamento por ID
      tags:
        - Equipamentos
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Equipamento encontrado
    put:
      summary: Atualiza um equipamento por ID
      tags:
        - Equipamentos
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numero_serie:
                  type: string
      responses:
        200:
          description: Equipamento atualizado com sucesso
    delete:
      summary: Remove um equipamento por ID
      tags:
        - Equipamentos
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Equipamento removido com sucesso
