tags:
  - name: Movimentação de estoque - Ações
    description: Gerenciamento de ações de movimentações de estoque

paths:
  /api/acoesmovimentacoes:
    get:
      summary: Lista todas as ações de movimentações de estoque
      tags:
        - Movimentação de estoque - Ações
      responses:
        200:
          description: Lista retornada com sucesso
    post:
      summary: Cria uma nova ação de movimentação de estoque
      tags:
        - Movimentação de estoque - Ações
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                descricao:
                  type: string
      responses:
        201:
          description: Registro criado com sucesso

  /api/acoesmovimentacoes/filtros:
    get:
      summary: Busca ações de movimentações por filtros
      tags:
        - Movimentação de estoque - Ações
      responses:
        200:
          description: Registros filtrados com sucesso

  /api/acoesmovimentacoes/{id}:
    get:
      summary: Busca ação por ID
      tags:
        - Movimentação de estoque - Ações
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Registro encontrado
    put:
      summary: Atualiza uma ação de movimentação por ID
      tags:
        - Movimentação de estoque - Ações
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                descricao:
                  type: string
      responses:
        200:
          description: Registro atualizado com sucesso
    delete:
      summary: Remove uma ação por ID
      tags:
        - Movimentação de estoque - Ações
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Registro removido com sucesso
