tags:
  - name: Movimentação de estoque - Histórico
    description: Gerenciamento de histórico de movimentações de estoque

paths:
  /api/historicomovimentacoes:
    get:
      summary: Lista o histórico de movimentações de estoque
      tags:
        - Movimentação de estoque - Histórico
      responses:
        200:
          description: Lista retornada com sucesso
    post:
      summary: Cria um novo registro no histórico
      tags:
        - Movimentação de estoque - Histórico
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                equipamento_id:
                  type: integer
                usuario_id:
                  type: integer
                acao_id:
                  type: integer
                data_movimentacao:
                  type: string
                observacao:
                  type: string
      responses:
        201:
          description: Registro criado com sucesso

  /api/historicomovimentacoes/filtros:
    get:
      summary: Busca registros do histórico por filtros
      tags:
        - Movimentação de estoque - Histórico
      responses:
        200:
          description: Registros filtrados com sucesso

  /api/historicomovimentacoes/{id}:
    get:
      summary: Busca registro do histórico por ID
      tags:
        - Movimentação de estoque - Histórico
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Registro encontrado
    put:
      summary: Atualiza um registro do histórico por ID
      tags:
        - Movimentação de estoque - Histórico
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                equipamento_id:
                  type: integer
                usuario_id:
                  type: integer
                acao_id:
                  type: integer
                data_movimentacao:
                  type: string
                observacao:
                  type: string
      responses:
        200:
          description: Registro atualizado com sucesso
    delete:
      summary: Remove um registro do histórico por ID
      tags:
        - Movimentação de estoque - Histórico
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Registro removido com sucesso
