tags:
  - name: Equipamentos
    description: Gerenciamento de equipamentos

paths:
  /api/equipamentos:
    get:
      summary: Lista todos os registros de equipamentos
      tags:
        - Equipamentos
      responses:
        200:
          description: Lista retornada com sucesso
    post:
      summary: Cria um novo equipamento
      tags:
        - Equipamentos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numero_serie:
                  type: string
      responses:
        201:
          description: Registro criado com sucesso

  /api/equipamentos/filtros:
    get:
      summary: Busca equipamentos por filtros
      tags:
        - Equipamentos
      responses:
        200:
          description: Registros filtrados com sucesso

  /api/equipamentos/{id}:
    get:
      summary: Busca equipamento por ID
      tags:
        - Equipamentos
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Registro encontrado
    put:
      summary: Atualiza um equipamento por ID
      tags:
        - Equipamentos
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                numero_serie:
                  type: string
      responses:
        200:
          description: Registro atualizado com sucesso
    delete:
      summary: Remove um equipamento por ID
      tags:
        - Equipamentos
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Registro removido com sucesso
