tags:
  - name: Termos gerados
    description: Gerenciamento de termos gerados

paths:
  /api/termosgerados:
    get:
      summary: Lista todos os termos gerados
      tags:
        - Termos gerados
      responses:
        200:
          description: Lista retornada com sucesso
    post:
      summary: Gera um novo termo com base em um template
      tags:
        - Termos gerados
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                termo_id:
                  type: integer
                template_id:
                  type: integer
                caminho_pdf:
                  type: string
                data_geracao:
                  type: string
      responses:
        201:
          description: Registro criado com sucesso

  /api/termosgerados/filtros:
    get:
      summary: Busca termos gerados por filtros
      tags:
        - Termos gerados
      responses:
        200:
          description: Registros filtrados com sucesso

  /api/termosgerados/{id}:
    get:
      summary: Busca termo gerado por ID
      tags:
        - Termos gerados
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Registro encontrado
    put:
      summary: Atualiza um termo gerado por ID
      tags:
        - Termos gerados
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                termo_id:
                  type: integer
                template_id:
                  type: integer
                caminho_pdf:
                  type: string
                data_geracao:
                  type: string
      responses:
        200:
          description: Registro atualizado com sucesso
    delete:
      summary: Remove um termo gerado por ID
      tags:
        - Termos gerados
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Registro removido com sucesso
